server:
  port: 8082

spring:
  application:
    name: microservice
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  jmx:
    enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/microservice?allowPublicKeyRetrieval=true&sslMode=DISABLED
    username: root
    password: 12345678

